# Generated by Django 4.2.7 on 2023-11-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='governagency',
            name='email',
        ),
        migrations.RemoveField(
            model_name='governagency',
            name='senha',
        ),
    ]
