# Generated by Django 4.2.7 on 2023-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_email_remove_company_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
    ]
